# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: tenstorrent
      url-base: https://github.com/tenstorrent
    - name: tenstorrent-forks
      url-base: https://github.com/tenstorrent-forks

  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: librpmi
      remote: tenstorrent-forks
      path: modules/lib/librpmi
      revision: 23e94f7007731e91be4de7c1d9c8c48b2173f6a2
    - name: zephyr
      remote: tenstorrent
      repo-path: zephyr-fork
      revision: 68672ece76e299ae6f1711586fb4756390ffe574
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - libmctp
          - mbedtls
          - mcuboot
          - nanopb
          - segger
          - tf-psa-crypto
  # zephyr-keep-sorted-stop

  group-filter:
    - +optional
